BASE = 0.4
R_RADIUS = BASE/5
R_LENGTH = BASE
R_WLENGTH = R_RADIUS
R_ALENGTH = 2.5*R_RADIUS
R_WIDTH  = BASE/2
R_HEIGHT = BASE/5

PED_LENGTH = 0.4
PED_WIDTH = PED_LENGTH
PED_HEIGHT = 7*BASE/10

PLT_LENGTH = 2
PLT_WIDTH = PLT_LENGTH
PLT_HEIGHT = 0.1

PLT_COMP_LENGTH = 2
PLT_COMP_WIDTH = PLT_COMP_LENGTH/2.5
PLT_COMP_HEIGHT = 0.1

PLT_WGT_LENGTH = PLT_LENGTH/5
PLT_WGT_WIDTH = PLT_WGT_LENGTH
PLT_WGT_HEIGHT = PLT_WGT_LENGTH

eval_time = 500
swm_size = 3
pop_size = 25
num_envs = 1
num_iter = 50
inj_thd = 0.12

