BASE = 0.4
R = BASE/5
A = 0.8*(BASE + R)

PED_LENGTH = 0.4
PED_WIDTH = PED_LENGTH
PED_HEIGHT = 7*BASE/10

PLT_LENGTH = 2
PLT_WIDTH = PLT_LENGTH
PLT_HEIGHT = 0.1

PLT_WGT_LENGTH = PLT_LENGTH/5
PLT_WGT_WIDTH = PLT_WGT_LENGTH
PLT_WGT_HEIGHT = PLT_WGT_LENGTH

eval_time = 450
swm_size = 3
pop_size = 10
num_envs = 1
num_gens = 100

